repos:
  - repo: local
    hooks:
      - id: format-func-definitions
        name: Format function definitions with type hints
        entry: python scripts/format_func_definitions.py
        language: system
        types: [python]
        pass_filenames: true

  # Import sorting
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0  # Use the latest stable version
    hooks:
      - id: isort
        name: isort
        entry: isort
        language: system
        types: [python]
        args: [--profile=black]  # Use black profile for compatibility

  # Code formatting
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black

  - repo: local
    hooks:
    - id: ruff
      name: Ruff
      entry: ruff check
      language: system
      types: [python]
      args: [--fix]
    - id: Pytest
      name: pytest
      entry: pytest
      language: system
      types: [python]
      pass_filenames: false
      always_run: true
